import React from "react";
export default function AboutMe() {
  return(
    <>
    <div className="aboutContainer">
      <p className="aboutParagraph">Hello! I'm Carlos R. Cáceres Martínez, a dedicated and dynamic Full Stack Web Developer with a strong affinity for solving complex problems and delivering robust, scalable web solutions. My journey into the vibrant world of technology has been marked by continuous learning and the proactive pursuit of innovative solutions.</p>
      <p className="aboutParagraph">My formal education began at Coding Dojo, Bellevue, Washington, where I received a certification in Python and delved deep into the fascinating realm of full stack web development. This was followed by an enriching stint at the University of Washington, Seattle, where I obtained a Full Stack Web Development certification, specializing in JavaScript.</p>
      <p className="aboutParagraph">I'm adept in a host of programming languages and tools, such as Python (Django), JavaScript (Express + Node JS), and numerous front-end technologies like React JS, Bootstrap, TailWind CSS, and JQuery. This versatility enables me to create dynamic, user-centric web applications that meet a wide range of requirements.</p>
      <p className="aboutParagraph">One of my key strengths lies in serverless computing. I've built numerous applications leveraging serverless architectures with Google Firebase and AWS Lambda, linked with AWS API Gateway. The serverless approach allows me to create scalable, cost-effective solutions that don't compromise on performance or security.</p>
      <p className="aboutParagraph">My expertise also spans across various databases, both SQL and No-SQL, allowing me to choose the best-suited database technology depending on the project requirements. I have experience working with Python ORM, SQLite3, MySQL, Google Firestore, MongoDB, and more.</p>
      <p className="aboutParagraph">As for the aesthetic appeal and usability of web applications, I often turn to tools like Balsamiq for design organization and wireframing. Once an application is ready for deployment, I leverage platforms like AWS EC2, Heroku, Netlify, or Ngrok, depending on the project's needs.</p>
      <p className="aboutParagraph">I'm also comfortable with testing frameworks such as Jest and ESLint and rely on GitHub for efficient version control. Being familiar with Linux and Windows operating systems, I usually work in IDEs like VS Code and VIM.</p>
      <p className="aboutParagraph">As part of my commitment to the tech community, I regularly participate in hackathons and networking events. These experiences not only challenge me and refine my technical abilities but also allow me to learn from peers and industry leaders. They're a testament to my teamwork, effective time management, and adaptability.</p>
      <p className="aboutParagraph">I'm bilingual, fluent in both English and Spanish, a trait that enhances my communication in the diverse tech world. I'm known for my positivity, patience, and being a dependable team player. As I look forward to each new project, I'm always excited about what I might learn next. Currently, I'm broadening my horizons with PostgreSQL, Google Cloud, Mac OS, and Swift.</p>
      <p className="aboutParagraph">Beyond my technical repertoire, my creativity also finds an outlet in video editing with Adobe Premiere Pro, photo editing with Adobe Light Room, and drawing/icon making with Adobe Illustrator.</p>
      <p className="aboutParagraph">With a solid blend of skills, certifications, a proactive attitude, and a keen desire to keep learning and growing, I am ready to make meaningful contributions to compelling web development projects. I look forward to the opportunity of turning the challenges that come my way into successful end products while also expanding my knowledge base.</p>
    </div>
    </>
  )
}